export type LogData = {
  address: string;
  latitude: number;
  longitude: number;
  diveType: 'SNORKEL' | 'FREEDIVING' | 'SCUBA';
  diveAt: string;
  score: 0 | 1 | 2 | 3 | 4 | 5;
  review: string;
  isPublic: boolean;
  hashTag?: string[];
  approachType?: 'BEATCH' | 'BOAT' | 'ETC';
  surfaceFlow?: 'STRONG' | 'MIDDLE' | 'WEAK';
  deepFlow?: 'STRONG' | 'MIDDLE' | 'WEAK';
  waterTemp?: number;
  temp?: number;
  beforeTank?: number;
  afterTank?: number;
  diveDepth?: number;
  pointDepth?: number;
  diveTime?: number;
  decompressionTime?: number;
  distanceView?: number;
};
